#!/bin/bash

#Author: Manqoba Makhoba
#Date Created: 10/06/2023
#Last modified: 10/06/23

# Description
# Creates a backup in ~/Documents folder of all files in the documents directory

# Usage:
# backup_script 

echo "hello ${USER^}"
echo "I will now backup-up your Documents directory, $HOME/Documents>"

currentdir=$(pwd)

echo "script is running in $currentdir , backup will be saved here"

tar -cvf $currentdir/documents_backup_"$(date +%d-%m-%Y_%H-%M-%S)".tar $HOME/Documents/* 2>/dev/null

echo "backup complete"
exit 0
