#!/bin/bash

#Author: Manqoba Makhoba
#Date Created: 10/06/2023
#Last modified: 10/06/23

# Description
# Creates a backup in ~/Documents folder of all files in the documents directory

# Usage:
# backup_script

tar -cvf ~/Documents/documents_backup_"$(date +%d-%m-%Y_%H-%M-%S)".tar ~/Documents/* 2>/dev/null
exit 0
